apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fleet-simple-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fleet-simple-app
  endpoints:
  - port: web
